# vim:ft=kitty

## name: Flexoki (Dark)
## author: Kepano
## license: MIT
## upstream: https://raw.githubusercontent.com/kepano/flexoki/main/kitty/flexoki_dark.conf
## blurb: An inky color scheme for prose and code

# The basic colors
foreground              #fffcf0
background              #100f0f
selection_foreground    #FFFCF0
selection_background    #403E3C

# Cursor colors
cursor                  #fffcf0
cursor_text_color       #100F0F

# kitty window border colors
active_border_color     #AF3029
inactive_border_color   #403E3C

# Tab bar colors
active_tab_foreground   #FFFCF0
active_tab_background   #403E3C
inactive_tab_foreground #878580
inactive_tab_background #282726

# The basic 16 colors
# black
color0 #100F0F
color8 #6F6E69

# red
color1 #e5938f
color9 #e3948d

# green
color2  #91b610
color10 #9cb242

# yellow
color3  #d3a001
color11 #d0a215

# blue
color4  #7aabe5
color12 #82aed4

# magenta
color5  #df91bd
color13 #de92b9

# cyan
color6  #33bbb0
color14 #40baaf

# white
color7  #f2f0e5
color15 #fffcf0
