# Based on Lavandula with darker purple accents for prompts
background            #050014
foreground            #e2e0e7
cursor                #facc15
cursor_text_color     #000000
selection_background  #36323b
selection_foreground  #050014
color0                #2e1065
color8                #4c1d95
color1                #f87171
color9                #fca5a5
color2                #22c55e
color10               #16a34a
color3                #facc15
color11               #fde047
color4                #8b5cf6
color12               #b794f6
color5                #9333ea
color13               #c084fc
color6                #7c3aed
color14               #a78bfa
color7                #d4d4d8
color15               #fafafa
